site_name: tomarkdown
site_url: https://berlinade.gitlab.io/tomarkdown
site_dir: public

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Doc of demo1 (my_script.py):
    - my_script: pages/demo1/my_script.md
    - my_script.a_class_generator: pages/demo1/my_script.a_class_generator.md
    - my_script.TopLevel: pages/demo1/my_script.TopLevel.md
    - my_script.TopLevel.MidLevel: pages/demo1/my_script.TopLevel.MidLevel.md
